const data = {
  races: [
    {
      id: 1,
      name: 'Hilltop Half-Marathon',
      description: 'Test your endurance in the hills of Nashville',
      event_type: '',
      start_time: '2021-04-05T17:37:01',
      end_time: '',
      start_location: 'The Hill Top at West 25th St',
      end_location: '',
      image_url: '',
      thumbnail_photo: '',
      difficulty_level: 'intermediate',
      running_distance: 13.5,
      leader: '',
      link: 'https://www.runnash.com/races/music-city-july-4th-virtual-5k/',
      attendees: 532,
      promoted: true,
      created_at: '',
      updated_at: '',
    },
    {
      id: 2,
      name: 'Second Chance Half-Marathon',
      description: 'We know many of you have diligently trained for this very day, so we are excited to present another opportunity for you to chase your 13.1 mile goal in Nashville on 4/24! This is a live, in-person race! Your participation will  provide hope for children aging out of orphanages in Haiti & Uganda.',
      event_type: '',
      start_time: '2021-04-05T17:37:01',
      end_time: '',
      start_location: '',
      end_location: '',
      image_url: '',
      thumbnail_photo: '',
      difficulty_level: '',
      running_distance: 13.1,
      leader: '',
      link: 'https://www.runnash.com/races/music-city-july-4th-virtual-5k/',
      attendees: 327,
      promoted: true,
      created_at: '',
      updated_at: '',
    },
    {
      id: 3,
      name: 'Music City 5k',
      description: `Kick off your Music City JULY 4TH celebration with a run through downtown Nashville! Bring the whole family to kick off your city celebrations with this traditional run/walk through downtown Nashville. \n

      All ages and fitness levels will love running past Nashville’s landmarks, like the new Music City Convention Center! \n

      Every participant will receive a commemorative medal & athletic tank top!`,
      event_type: '',
      start_time: '2021-04-05T17:37:01',
      end_time: '',
      start_location: '',
      end_location: '',
      image_url: '',
      thumbnail_photo: '',
      difficulty_level: '',
      running_distance: 3.2,
      leader: '',
      link: 'https://www.runnash.com/races/music-city-july-4th-virtual-5k/',
      attendees: 641,
      promoted: true,
      created_at: '',
      updated_at: '',

    },
  ],
  dailyRuns: [
    {
      id: 1,
      name: 'Centennial Park, West End Ave Entrance',
      description: 'Join us for a lesiurely early morning 5k along the lake in beautiful Centennial Park',
      event_type: '',
      start_time: '2021-04-05T10:30:00.000Z',
      end_time: '',
      start_location: '2500 West End Ave',
      end_location: '',
      image_url: '',
      thumbnail_photo: '',
      difficulty_level: 'beginner',
      running_distance: 13.5,
      leader: 'Jack McClain',
      link: 'https://www.runnash.com/races/music-city-july-4th-virtual-5k/',
      attendees: 532,
      promoted: true,
      created_at: '',
      updated_at: '',
    },
    {
      id: 2,
      name: 'Centennial Park, West End Ave Entrance',
      description: 'Join us for a lesiurely early morning 5k along the lake in beautiful Centennial Park',
      event_type: '',
      start_time: '2021-04-05T10:30:00.000Z',
      end_time: '',
      start_location: '2500 West End Ave',
      end_location: '',
      image_url: '',
      thumbnail_photo: '',
      difficulty_level: 'beginner',
      running_distance: 13.5,
      leader: 'Jack McClain',
      link: 'https://www.runnash.com/races/music-city-july-4th-virtual-5k/',
      attendees: 532,
      promoted: true,
      created_at: '',
      updated_at: '',
    },
    {
      id: 3,
      name: 'Centennial Park, West End Ave Entrance',
      description: 'Join us for a lesiurely early morning 5k along the lake in beautiful Centennial Park',
      event_type: '',
      start_time: '2021-04-05T10:30:00.000Z',
      end_time: '',
      start_location: '2500 West End Ave',
      end_location: '',
      image_url: '',
      thumbnail_photo: '',
      difficulty_level: 'beginner',
      running_distance: 13.5,
      leader: 'Jack McClain',
      link: 'https://www.runnash.com/races/music-city-july-4th-virtual-5k/',
      attendees: 532,
      promoted: true,
      created_at: '',
      updated_at: '',
    },
    {
      id: 4,
      name: 'Centennial Park, West End Ave Entrance',
      description: 'Join us for a lesiurely early morning 5k along the lake in beautiful Centennial Park',
      event_type: '',
      start_time: '2021-04-05T10:30:00.000Z',
      end_time: '',
      start_location: '2500 West End Ave',
      end_location: '',
      image_url: '',
      thumbnail_photo: '',
      difficulty_level: 'beginner',
      running_distance: 13.5,
      leader: 'Jack McClain',
      link: 'https://www.runnash.com/races/music-city-july-4th-virtual-5k/',
      attendees: 532,
      promoted: true,
      created_at: '',
      updated_at: '',
    },
  ],
};

export default data;
